# Use root/example as user/password credentials
version: '3.8'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: tyk_root
      MONGO_INITDB_ROOT_PASSWORD: 33r2Y4HE!G&LABm?Zq2+LnGVyTQDwq@$G&V!W$n7k2S8xtk$

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: tyk_admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: ExJ-#aYsrLRYRc@DqUbsh3xrX!GzM2n8

# docker-compose -f tyk_mondo.yml up
# or
# docker stack deploy -c tyk_mondo.yml mongo
